### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by atarashansky** [atarashansky/SAMap#1]
- [x] Clean up input and output.
- [x] Add function to analyze enriched genes.
- [x] Add function to output mapping tables.
- [x] Document code.
