### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by atarashansky** [atarashansky/SAMap#2]
- [x] Deeper documentation of exposed functions
- [x] More extensive tutorial notebooks and README
- [x] Organize `SAMap.py` into separate modules
- [x] Provide a Dockerfile for setting up the SAMap environment.
- [x] Make function to create sankey diagrams.
